apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: auto-upgrade-cronjob
spec:
  schedule: '*/15 * * * *'
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 0
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          volumes:
          - name: agent-pvc-storage
            persistentVolumeClaim:
              claimName: openhorizon-agent-pvc
          containers:
          - name: agent-auto-upgrade
            image: '__ImagePath__'
            command:
              - /bin/sh
              - '-c'
              - >-
                /usr/local/bin/auto-upgrade-cronjob.sh
            imagePullPolicy: Always
            volumeMounts:
            - mountPath: /var/horizon
              name: agent-pvc-storage
              subPath: horizon
            env:
            - name: CRONJOB_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          restartPolicy: Never
          serviceAccountName: __ServiceAccount__
          serviceAccount: __ServiceAccount__
